# Generated by Django 2.0.7 on 2018-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='영화 제목')),
                ('content', models.TextField(verbose_name='줄거리')),
                ('running', models.CharField(max_length=10, verbose_name='러닝타임')),
                ('age', models.CharField(max_length=10, verbose_name='나이제한')),
                ('reservationRate', models.CharField(max_length=10, verbose_name='예매율')),
                ('cast_set', models.ManyToManyField(to='watcha.Cast')),
                ('country_set', models.ManyToManyField(to='watcha.Country')),
                ('director_set', models.ManyToManyField(to='watcha.Director')),
                ('genre_set', models.ManyToManyField(to='watcha.Genre')),
            ],
        ),
    ]
