# Generated by Django 2.0.7 on 2018-08-04 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watcha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='순위'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='나이제한'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_set',
            field=models.ManyToManyField(blank=True, null=True, to='watcha.Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_set',
            field=models.ManyToManyField(blank=True, null=True, to='watcha.Country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_set',
            field=models.ManyToManyField(blank=True, null=True, to='watcha.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_set',
            field=models.ManyToManyField(blank=True, null=True, to='watcha.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reservationRate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='예매율'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='영화 제목'),
        ),
    ]
