# Generated by Django 2.0.7 on 2018-08-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0005_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
    ]
