# Generated by Django 2.0.7 on 2018-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0008_auto_20180819_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
