# Generated by Django 2.1 on 2018-08-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0011_auto_20180820_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watcha.Movie'),
        ),
    ]
