# Generated by Django 2.1 on 2018-08-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0012_score_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='movie',
        ),
        migrations.AlterField(
            model_name='score',
            name='movie_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watcha.Movie'),
        ),
    ]
