# Generated by Django 2.1 on 2018-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0013_auto_20180822_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='movie_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='영화 제목'),
        ),
    ]
